@startuml

class Task {
'attributes
    - name : SimpleStringProperty
    - date : String
    - status : String
    - statBool : boolean

'methods
    +Task(String name, boolean statBool)
    +Task(String name, String date, boolean statBool)
    +Task(String name, String date, String status)

    +setName(String name)
    +setDate(String date)
    +setStatus(boolean statBool)

    +getName() : String
    +getDate() : String
    +getStatus() : String
    +getStatusBool() : boolean
}

class ApplicationController{
'attributes
    - tableView : TableView<Task>
    - nameColumn : TableColumn<Task, String>
    - dateColumn : TableColumn<Task, String>
    - statusCol : TableColumn<Task, String>

    - private TextField nameField;
    - dateField : DatePicker
    - statusMessageTxt : Label
    - progressBar : ProgressBar

'methods
    -newTask()

    -openList()
    -downloadList()

    -showAll()
    -showCompleted()
    -showUncompleted()

    -deleteTask()
    -clearAll()

    -changeName()
    -changeDate()
    -changeStatus()

    -updateProgressBar()
    +initialize(URL url, ResourceBundle rb)
}

class TodoListApplication{
'methods
    +main(String[] args)
    +start(Stage stage)
}

@enduml